name: ML Regression CI

on:
  push:
    branches:
      - reg
      - hyper

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Regression
        run: |
          python regression.py || true
          python hyper_tuning.py || true
